import { ProductViewBreadcrumbs } from '../ProductViewBreadcrumbs/ProductViewBreadcrumbs.container';

export { ProductDescription } from '../../components/Product/ProductDescription/ProductDescription.component';
export { ProductContainer } from '../../components/Product/ProductView/ProductContainer/ProductContainer.component';
export { apiURL } from '../../apiURL';
export { GoBackButton } from '../../components/shared/GoBackButton/GoBackButton.component';
export { DropdownGroup } from '../DropdownGroup/DropdownGroup.Container';
export { default as ProductImage } from '../../components/ProductImage/ProductImage.component';
export { default as topSide } from '../../components/ProductImage/images/Picture2.png';
export { default as bigImage } from '../../components/ProductImage/images/Picture1.png';
export { default as middleSide } from '../../components/ProductImage/images/Picture3.png';
export { default as bottomSide } from '../../components/ProductImage/images/Picture4.png';
export { ProductViewWrapper } from '../../components/Product/ProductView/ProductViewWrappers/ProductViewWrapper/ProductViewWrapper.component';
export { ProductViewImageWrapper } from '../../components/Product/ProductView/ProductViewWrappers/ProductViewImageWrapper/ProductViewImageWrapper.component';
export { ProductViewReviewsWrapper } from '../../components/Product/ProductView/ProductViewWrappers/ProductViewReviewsWrapper/ProductViewReviewsWrapper.component';
export { ProductViewDescription } from '../../components/Product/ProductView/ProductViewWrappers/ProductViewDescription/ProductViewDescription.component';
export { ProductViewButtons } from './ProductViewButtons/ProductViewButtons.container';
export { RelatedItems } from '../RelatedItems/RelatedItems.Container';
export { ProductReviewsContainer } from '../ProductReviewContainer/ProductReviewsContainer';
export { ProductViewBreadcrumbs } from '../ProductViewBreadcrumbs/ProductViewBreadcrumbs.container';
