export { ProductDescription } from '../../components/Product/ProductDescription/ProductDescription.component';
export { ProductContainer } from '../../components/Product/ProductView/ProductContainer/ProductContainer.component';
export { apiURL } from '../../apiURL';
export { GoBackButton } from '../../components/shared/GoBackButton/GoBackButton.component';
export { DropdownGroup } from '../DropdownGroup/DropdownGroup.Container';
export { default as ProductImage } from '../../components/ProductImage/ProductImage.component';
export { default as topSide } from '../../components/ProductImage/images/Picture2.png';
export { default as bigImage } from '../../components/ProductImage/images/Picture1.png';
export { default as middleSide } from '../../components/ProductImage/images/Picture3.png';
export { default as bottomSide } from '../../components/ProductImage/images/Picture4.png';
export { ProductViewWrapper } from '../../components/Product/ProductView/ProductViewWrapper/ProductViewWrapper.component';
export { ProductViewDescription } from '../../components/Product/ProductView/ProductViewDescription/ProductViewDescription.component';
export { ProductViewButtons } from './ProductViewButtons/ProductViewButtons.container';
