name: Migrations

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Verify DB connection
        env:
          PORT: 33306
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done
      - name: Use Node.js 17.3.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.3.x
      - run: yarn
        env:
          CI: true
      - name: Run DB Migrations
        run: yarn workspace server db:setup
        env:
          MYSQL_HOST: '127.0.0.1'
          MYSQL_PORT: 33306
          MYSQL_USER: 'root'
          MYSQL_PASSWORD: 'password'
          MYSQL_DATABASE: 'test'
      - name: Run DB Migrations Rollback
        run: yarn workspace server db:clean
        env:
          MYSQL_HOST: '127.0.0.1'
          MYSQL_PORT: 33306
          MYSQL_USER: 'root'
          MYSQL_PASSWORD: 'password'
          MYSQL_DATABASE: 'test'

