name: Storybook

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 17.3.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.3.x
      - run: yarn install
        env:
          CI: true
      - name: Run Storybook
        run: yarn workspace client run storybook -- --ci --smoke-test --quiet
